#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

cleanCase0

rm -rf constant/triSurface
rm -f 0.orig/*_nd
rm -f 0.orig/nucBin
#------------------------------------------------------------------------------
